# Generated by Django 4.1 on 2024-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_price_product_max_price_product_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='long_description',
            field=models.JSONField(default=dict),
        ),
    ]
