# Generated by Django 4.1 on 2024-12-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_long_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_description',
        ),
        migrations.AddField(
            model_name='product',
            name='main_description',
            field=models.JSONField(default=list),
        ),
    ]
