# Generated by Django 4.1 on 2024-12-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_product_name_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='main_description',
        ),
        migrations.AddField(
            model_name='product',
            name='tags_list',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
