# Generated by Django 4.1 on 2024-12-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_main_description_product_tags_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags_list',
        ),
    ]
