# Generated by Django 4.1 on 2024-12-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_tags_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags_list',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
